---
 # file is parsed by inner-most keys only
 data:
     dataset: dips
     data_file: data/dips.csv
     data_path: /data/rsg/chemistry/rmwu/data/raw/binding/dips/pairs-pruned
 model:
     model_type: e3nn
     no_torsion: True
     no_batch_norm: True
 train:
     patience: 50
     epochs: 500
     #lr: 1.e-5
     #weight_decay: 0.
     #num_conv_layers: 4
