---
 # file is parsed by inner-most keys only
 data:
     dataset: dips
     data_file: data/dips.csv
     data_path: /data/rsg/chemistry/rmwu/data/raw/binding/dips/pairs-pruned
     resolution: residue
 model:
     model_type: e3nn
     no_torsion: True
     no_batch_norm: True
 train:
     patience: 20
     epochs: 200
     lr: 1.e-4
     weight_decay: 0.
     num_conv_layers: 2
